name: ipmsg build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  ipmsg:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Install Dependencies
        run: pod install
      - name: Build
        run: xcodebuild -workspace IPMessenger.xcworkspace -scheme IPMessenger -configuration Release build
